#docker-compose.yml
version: '3.8'
services:
  subgen:
    container_name: subgen2
    tty: true
    image: mccloud/subgen
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
       - "WHISPER_MODEL=large-v3-turbo"
       - "WHISPER_THREADS=4"
       - "PROCADDEDMEDIA=True"
       - "PROCMEDIAONPLAY=False"
       - "NAMESUBLANG=en"
       - "SKIPIFINTERNALSUBLANG=eng"
       - "WEBHOOKPORT=9000"
       - "CONCURRENT_TRANSCRIPTIONS=2"
       - "WORD_LEVEL_HIGHLIGHT=False"
       - "DEBUG=True"
       - "USE_PATH_MAPPING=False"
       - "TRANSCRIBE_DEVICE=cuda"
       - "CLEAR_VRAM_ON_COMPLETE=True"
       - "MODEL_PATH=/data/whisper/mccloud/subgen/models"
       - "UPDATE=True"
       - "APPEND=False"
       - "USE_MODEL_PROMPT=False"
       - "CUSTOM_MODEL_PROMPT="
       - "LRC_FOR_AUDIO_FILES=True"
       - "CUSTOM_REGROUP=cm_sl=84_sl=42++++++1"
    volumes:
       - "${APPDATA}/subgen/models:/data/whisper/mccloud/subgen/models"
    ports:
       - "9000:9000"
